{application,clickhouse_ecto,
             [{description,"ClickHouse driver for Elixir (uses ODBC)."},
              {modules,['Elixir.ClickhouseEcto',
                        'Elixir.ClickhouseEcto.Connection',
                        'Elixir.ClickhouseEcto.Helpers',
                        'Elixir.ClickhouseEcto.Migration',
                        'Elixir.ClickhouseEcto.Query',
                        'Elixir.ClickhouseEcto.QueryString',
                        'Elixir.ClickhouseEcto.Storage',
                        'Elixir.ClickhouseEcto.Structure',
                        'Elixir.ClickhouseEcto.Type']},
              {registered,[]},
              {vsn,"0.1.1"},
              {applications,[kernel,stdlib,elixir,logger,ecto]}]}.
